apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-api-gateway-depl
  namespace: ordering-system
  labels:
    app: ocelot-api-gateway
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
        - name: ocelot-api-gateway
          image: samboers/ocelotapigateway:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-clusterip-srv
  namespace: ordering-system
spec:
  type: ClusterIP
  selector:
    app: ocelot-api-gateway
  ports:
  - name: ocelot-api-gateway
    protocol: TCP
    port: 80
    targetPort: 80

