apiVersion: v1
kind: Service
metadata:
  name: ocelot-service-loadbalancer
  labels:
    app: ocelot-api-gateway
spec:
  selector:
    app: ocelot-api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
