apiVersion: v1
kind: Service
metadata:
  name: ocelot-loadbalancer-srv 
  namespace: ordering-system
spec:
  type: LoadBalancer 
  selector:
    app: ocelot-api-gateway
  ports:
    - name: ocelot-api-gateway
      protocol: TCP
      port: 80
      targetPort: 80