apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-depl
  namespace: ordering-system
  labels:
    app: ocelot-api-gateway
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
        - name: ocelot-api-gateway
          image: gcr.io/ordering-system-404411/ocelotapigateway
          imagePullPolicy: Always


