apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-depl
  labels:
    app: ocelot-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
        - name: ocelot-api-gateway
          image: gcr.io/ordering-system-404411/ocelotapigateway
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-service
  labels:
    app: ocelot-api-gateway
spec:
  selector:
    app: ocelot-api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

